### ISSUE TITLE
Problem with selectors (additional mapping)

### ISSUE THREAD

**Issue by oleg-demkovych** [slavaGanzin/linkedin-scrapper#1]
I'm try to replace selectors from mapping.coffee file (replace by new linkedin selectors), but nothing work. Then i try to add additional mapping obj before send request, but receive empty fields. How to solve it? 

http://take.ms/NSEEE

```
   var additionalMapping = {
    sections: {
        name: {
          selector: ".full-name",
        },
        position: {
          selector: "#location .industry"
        },
        summary: {
          selector: ".summary .description"
        }
      },
      defaultSectionMapping: {
        field: '.full-name'
      }
    }

    var callback = function(obj) {
      console.log(obj.result);
    };
    var scrapper = require('linkedin-profile');
    scrapper('https://www.linkedin.com/in/bohdansharipov', callback, additionalMapping);


```

**Comment by slavaGanzin** [comment]
AdditionalMapping wasn't working before - my fault. Released new version. Try it.
You can always create PR to fix changed selectors. Thanks

**Comment by ghost** [comment]
@slavaGanzin It's my mistake. Working good. I use detail profile link, but need public.
